import {
  Clarinet,
  Tx,
  Chain,
  Account,
  types,
} from "https://deno.land/x/clarinet@v0.14.0/index.ts";
import { assertEquals } from "https://deno.land/std@0.90.0/testing/asserts.ts";

Clarinet.test({
  name: "Ensure that <...>",
  async fn(chain: Chain, accounts: Map<string, Account>) {
    let deployerWallet = accounts.get("deployer") as Account;
    let wallet1 = accounts.get("wallet_1") as Account;
    let wallet2 = accounts.get("wallet_2") as Account;

    chain.mineEmptyBlockUntil(1);

    let block;
    chain.mineBlock([
      Tx.contractCall(
        `optimized-big-random`,
        "test-element-at",
        [],
        deployerWallet.address
      ),
    ]);

    let nums: any[] = [];
    for (let i = 0; i < 40; i++) {
      block = chain.mineBlock([
        Tx.contractCall(
          `optimized-big-random`,
          "mint",
          [],
          deployerWallet.address
        ),
      ]);

      // if (nums.indexOf(block.receipts[0].result.expectOk()) != -1) {
      //     console.log("NOOOO");
      // } else {
      //     nums.push(block.receipts[0].result.expectOk())
      // }
    }
  },
});

// Clarinet.test({
//     name: "Ensure that <...>",
//     async fn(chain: Chain, accounts: Map<string, Account>) {
//         let deployerWallet = accounts.get("deployer") as Account;
//         let wallet1 = accounts.get("wallet_1") as Account;
//         let wallet2 = accounts.get("wallet_2") as Account;

//         chain.mineEmptyBlockUntil(1);

//         let block;
//         block = chain.mineBlock([
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//         ]);

//         block.receipts[10].result.expectOk()

//         block = chain.mineBlock([
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//         ]);

//         block.receipts[30].result.expectOk()
//         block.receipts[31].result.expectErr()

//         block = chain.mineBlock([
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//             Tx.contractCall(
//                 `optimized-big-random`,
//                 "mint",
//                 [],
//                 deployerWallet.address
//             ),
//         ]);

//         block.receipts[0].result.expectOk()
//         block.receipts[31].result.expectErr()

//         let finalReceipt: any = { result: {} as any};
//         for(let i = 0; i < 400; i++) {
//             block = chain.mineBlock([
//                 Tx.contractCall(
//                     `optimized-big-random`,
//                     "mint",
//                     [],
//                     deployerWallet.address
//                 )
//             ]);
//             finalReceipt = block.receipts[0]
//         }
//         finalReceipt.result.expectErr()

//     },
// });
